version: "3.8"

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile 
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000:3000-3005"

  db:
    image: mongo
    volumes:
      - mongodata:/data/db

volumes: 
    mongodata: