version: "3.9"

services:
  app:
    build:
        context: .
        dockerfile: Dockerfile 
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "3000-3001:3000"
    deploy:
      replicas: 2

  db:
    image: mongo
    volumes:
      - mongodata:/data/db

  lb:
    build:
      context: .
      dockerfile: nginxDockerfile
    ports: 
      - "8080:80"

volumes: 
    mongodata: